import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Biblioteca de jogos - By: Isaque Chaves',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className="{inter.className} p-16">{children}</body>
    </html>
  )
}
